def format_item_data(request_data):
    item_data = {
        "tpin": request_data.get("tpin"),
        "bhfId": request_data.get("bhfId"),
        "itemCd": request_data.get("itemCd"),
        "itemClsCd": request_data.get("itemClsCd"),
        "itemTyCd": request_data.get("itemTyCd"),
        "itemNm": request_data.get("itemNm"),
        "itemStdNm": request_data.get("itemStdNm", ''),
        "orgnNatCd": request_data.get("orgnNatCd"),
        "pkgUnitCd": request_data.get("pkgUnitCd"),
        "qtyUnitCd": request_data.get("qtyUnitCd"),
        "vatCatCd": request_data.get("vatCatCd"),
        "iplCatCd": request_data.get("iplCatCd"),
        "tlCatCd": request_data.get("tlCatCd"),
        "exciseTxCatCd": request_data.get("exciseTxCatCd"),
        "btchNo": request_data.get("btchNo", ''),
        "bcd": request_data.get("bcd", ''),
        "dftPrc": request_data.get("dftPrc"),
        "manufacturerTpin": request_data.get("manufacturerTpin", ''),
        "manufacturerItemCd": request_data.get("manufacturerItemCd", ''),
        "rrp": request_data.get("rrp", 0),
        "svcChargeYn": request_data.get("svcChargeYn", "N"),
        "rentalYn": request_data.get("rentalYn", "N"),
        "addInfo": request_data.get("addInfo", ''),
        "sftyQty": request_data.get("sftyQty", 0),
        "isrcAplcbYn": request_data.get("isrcAplcbYn", "N"),
        "useYn": request_data.get("useYn"),
        "regrNm": request_data.get("regrNm"),
        "regrId": request_data.get("regrId"),
        "modrNm": request_data.get("modrNm", ''),
        "modrId": request_data.get("modrId", ''),
    }

    return item_data
